name: verify-runner
on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  ping:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - run: 'Write-Host "Runner OK. User: $env:USERNAME"'
      - run: docker --version
